baseURL = "http://gdquest.com/"
languageCode = "en-us"
title = "GDQuest"

metaDataFormat = "yaml"

paginate = 6
paginatePath = "page"

[[menu.main]]
identifier  = "tutorial"
name        = "Tuts"
url         = "/tutorial/"
weight      = 1

[[menu.main]]
identifier  = "product"
name        = "products"
url         = "/product/"
weight      = 2

[[menu.main]]
identifier  = "about"
name        = "About"
url         = "/about/"
weight      = 3

[[menu.main]]
identifier  = "news"
name        = "News"
url         = "/post/"
weight      = 3

[params.shop_link]
name        = "Shop"
url         = "https://gumroad.com/gdquest"


[permalinks]

[taxonomies]
tags = "tags"
category = "category"
headerbanner = "banner"

[author]
name = "Nathan Lovato"
email = "nathan@gdquest.com"


# Site parameters
[params]
topline = "The Game Design Quest"
home = "home"
highlight = "default"
stylesheet = "concise.css"


# Social network names for Meta tag SEO
twitter = "NathanGDquest"
googleplus = "Gdquest"

[params.social.1]
link = "https://www.youtube.com/c/gdquest"
icon = "youtube"
description = "GDquest Youtube channel"
[params.social.2]
link = "https://www.facebook.com/gdquest"
icon = "facebook"
description = "GDquest Facebook page"
[params.social.3]
link = "https://twitter.com/NathanGDquest"
icon = "twitter"
description = "GDquest Twitter page"


[blackfriday]
angledQuotes = true
fractions = false
hrefTargetBlank = false
latexDashes = true
plainIdAnchors = true
extensions = []
extensionmask = []

