name = "GDquest"
license = "MIT"
licenselink = "https://github.com/mmrath/hugo-bootstrap/LICENSE.md"
description = "A hugo theme using bootstrap 3, pingendo's css, font-awesome"
homepage = "https://github.com/mmrath/hugo-bootstrap"
tags = ["blog", "technical", "personal"]
features = ["blog", "technical", "personal"]
min_version = 0.15

[author]
    name = "Nathan Lovato"
    homepage = "http://gdquest.com"

[original]
    author = "Murali Rath"
    homepage = "http://mmrath.com"
    repo = "https://github.com/mmrath/hugo-bootstrap"
